Add Vagrant support.
qedsoftware/ansible-socorro pull request #3
Opened 2017-07-10 17:41 UTC by wojtex

1. Moved role-related directories to `roles/socorro` - I think it is more intuitive, readable and does not depends on name of directory and maybe contents of parent directory. If somebody want to use these scripts, they can copy or symlink a directory.

2. Added Vagrant box configuration to easily experiment with Ansible configuration.

2017-07-10 17:57 UTC, ruslo requested changes

2017-07-10 17:57 UTC, ruslo commented on ansible.cfg
> +roles_path=roles/
Currently code fits recommended directory structure:
* https://galaxy.ansible.com/intro#share

I think this part should not be changed.

2017-07-10 18:55 UTC, ruslo requested changes
Please fix Travis CI testing.

2017-07-10 18:55 UTC, ruslo commented on tasks/main.yml
> +  when: inventory_hostname!='vagrant'
I don't think relying of inventory file name is a good idea. This should be some condition variable

```
- debug: msg="..."
  when: ansible_socorro_use_vargant
```

2017-07-10 18:55 UTC, ruslo commented on prod.yml
> +- hosts: vagrant
I don't know what exactly is happenning here but according to the code it looks like something quite orthogonal to socorro installation. Why it's not a separate role?

2017-07-12 09:42 UTC, wojtex commented
According to the discussion with @ruslo, Vagrant files will be moved to separate repository.

2017-07-12 09:42 UTC, closed without merging